version: "3.8"

name: "Docker-Udemy"

services:
  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: ./apps/app/Dockerfile
    ports:
      - '3001:80'
    networks:
      - my-test

  api:
    container_name: "api"
    restart: always
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - ./dist/apps/api:/opt/app/dist
    env_file:
      - ./envs/.api.env
      - ./envs/.mongo.env
      - ./envs/.rmq.env
    command: npm run start:prod

    depends_on:
      - rmq
    ports:
      - 8000:8000
    networks:
      - my-test
    links:
      - rmq
     
  converter:
    extends:
      file: ./docker/docker-compose.api.yaml
      service: converter
    depends_on:
      - rmq

  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    restart: always
    volumes:
      - rmq:/etc/rmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 25672:5672
      - 15672:15672
    networks:
      - my-test

networks:
  my-test:
    driver: bridge

volumes:
  rmq:
