version: "3.8"

services:
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    restart: always
    volumes:
      - rmq:/etc/rmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 25672:5672
      - 15672:15672
    networks:
      - my-test

networks:
  my-test:
    driver: bridge

volumes:
  rmq:
